# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"makeMixedDataFrame": "00_core.ipynb",
         "getCrashes": "00_core.ipynb",
         "is_numeric": "00_core.ipynb",
         "drop_singletons": "00_core.ipynb",
         "discretize": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://ctwardy.github.io/nbdev-demo #mydemo/"

git_url = "https://github.com/ctwardy/nbdev-demo #mydemo/tree/master/"

def custom_doc_links(name): return None
